### ISSUE TITLE
Add default header image for theme.

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/escapade-theme#3]
Please add a single default header image to match the original design. Please optimize this image for the web as well.

**Comment by danielimmke** [comment]
This one took a little while. It's actually kind of awkward to test, because once you hit "hide image" it actually takes that to mean you don't want _any_ header image instead of the default one and there doesn't seem to be any UI way to get back to the default once you change it short of activating on a different install.

Which is what I ended up doing, so confirmed working. I also added a conditional in for the widget area so it only displays if the default or a manually uploaded header image have been added.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;e9pkmwH4&#x2F;24-escapade-travel-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Escapade (Travel Theme)</a>
